title: Eduardo Souza
url: "https://eduardodx.net"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: no
footer_url: "https://github.com/bk2dcradle"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass
